# Variables Scopes: Root level, Stage level, Job level

variables:
  global_variable: 'Root level Variable' # Root Level, this is aviailable to all stages and jobs

stages:
- stage: variable_scope_stage
  jobs:
  - job: variable_scope_job
    variables:
      job_variable: 'Job level Variable' # Job Level, this is available to all steps in this job
    steps:
    - script: |
            echo $(global_variable)
            echo $(job_variable)
            echo ${{ variables.global_variable }}
            echo ${{ variables.job_variable }}
            echo $GLOBAL_VARIABLE
            echo $JOB_VARIABLE
      displayName: 'Variables scope'
 
